server.port=9000
spring.application.name=eserver
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=192.168.0.101
eureka.client.service-url.defaultZone=http://192.168.0.101:9000/eureka
logging.level.com.netflix.discovery=OFF
logging.pattern.console=%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n
eureka.renewalPercentThreshold=0.85

logging.level.com.netflix.eureka=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG