spring.application.name=users
eureka.instance.hostname=192.168.0.101

server.port=8083

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://192.168.0.101:9000/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=192.168.0.101

logging.level.com.netflix.eureka=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=false
spring.liquibase.defaultSchema=public
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml

jwt.access.secret=your-very-long-secret-key-at-least-32-characters-access
jwt.refresh.secret=your-very-long-secret-key-at-least-32-characters-refresh

accessTokenExpiration=3000000
refreshTokenExpiration=86400000