spring.application.name=product-category
eureka.instance.hostname=192.168.0.101

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://192.168.0.101:9000/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=192.168.0.101

logging.level.com.netflix.eureka=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG

url=jdbc:postgresql://localhost:5432/product_category
username=postgres
password=admin
driver=org.postgresql.Driver
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
referenceUrl=hibernate:spring:com.example.products.models?dialect=org.hibernate.dialect.PostgreSQLDialect
#mvn liquibase:diff "-Dliquibase.diffChangeLogFile=src/main/resources/db.changelog-new.xml"
#mvn liquibase:update