spring.application.name=api-gateway
server.port=8089

eureka.client.enabled=true


eureka.instance.hostname=192.168.0.101
 
# Eureka client config
eureka.client.service-url.defaultZone=http://192.168.0.101:9000/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=192.168.0.101




 
# Optional: timeout config
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30